#
#  Settings for Soulbound in general
###
General:
    # Allow Soulbound to report on basic anonymous usage
    Stats_Tracking: true
    # Should Soulbound print out debug messages?
    Verbose_Logging: false
    # Should Soulbound over-write configs to update, or make new ones ending in .new?
    Config_Update_Overwrite: true
Soulbound:
    Feedback_Messages_Enabled: true
    Prevent_Item_Drop: false
    Delete_On_Drop: false
    Infinite_Durability: false
    Blocked_Commands:
        /blockedcommand
    Commands_Bind_When_Used:
        /enchant