name: Soulbound
version: ${project.version}
author: TfT_02
main: com.me.tft_02.soulbound.Soulbound
description: Soulbound items for your RPG servers!
softdepend: [EpicBossRecoded, LoreLocks, MythicDrops]
commands:
   soulbound:
      description: Usage /soulbound
      permission-message: You don't have <permission>
   bind:
      description: Usage /bind
      alias: bound
      permission: soulbound.commands.bind
      permission-message: You don't have <permission>
   bindonpickup:
      description: Usage /bindonpickup
      permission: soulbound.commands.bindonpickup
      permission-message: You don't have <permission>   
   bindonuse:
      description: Usage /bindonuse
      permission: soulbound.commands.bindonuse
      permission-message: You don't have <permission>   
   bindonequip:
      description: Usage /bindonequip
      permission: soulbound.commands.bindonequip
      permission-message: You don't have <permission>   
   unbind:
      description: Usage /unbind
      alias: unbound
      permission: soulbound.commands.unbind
      permission-message: You don't have <permission>
permissions:
    soulbound.commands.all:
        description: Gives access to the Soulbound commands
        default: op
        children:
            soulbound.commands.bind: true
            soulbound.commands.bindonpickup: true
            soulbound.commands.bindonuse: true
            soulbound.commands.bindonequip: true
            soulbound.commands.unbind: true
            soulbound.commands.reload: true
            soulbound.updatecheck: true
    soulbound.pickup.bypass:
        description: Users with this permission will be able to pickup Soulbound items that do not belong to them.
        default: false
    soulbound.items.keep_on_death:
        description: Users with this permission will keep their Soulbound items after dying
        default: false
    soulbound.items.delete_on_death:
        description: Users with this permission will have their Soulbound items deleted on death
        default: false
    soulbound.updatecheck:
        description: Users with this permission will receive a notification when there is a new version available.
        default: op